language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script:
  - yarn test:format
  - yarn lint
  - yarn build
  - yarn lint:extension
  - yarn build:extension
  - yarn test:ci
